"""Initial migration

Revision ID: 4d7efbb40ac6
Revises: 
Create Date: 2022-06-10 19:56:50.069902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7efbb40ac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_column('blog_posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('author', sa.VARCHAR(length=250), nullable=False))
    op.drop_column('blog_posts', 'author_id')
    # ### end Alembic commands ###
