"""Initial

Revision ID: 78851f9ed7e4
Revises: 4d7efbb40ac6
Create Date: 2022-06-10 20:04:54.874823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78851f9ed7e4'
down_revision = '4d7efbb40ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_column('blog_posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('author', sa.VARCHAR(length=250), nullable=False))
    op.drop_column('blog_posts', 'author_id')
    # ### end Alembic commands ###
