"""Initial migrate

Revision ID: b82497fafa59
Revises: d70acfdc7aaa
Create Date: 2022-06-11 12:27:38.948820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82497fafa59'
down_revision = 'd70acfdc7aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blog_posts', 'users', ['author_id'], ['id'])
    op.add_column('comments', sa.Column('blog_post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'blog_posts', ['blog_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog_post_id')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    # ### end Alembic commands ###
