"""Initial

Revision ID: d70acfdc7aaa
Revises: 78851f9ed7e4
Create Date: 2022-06-11 08:57:48.681392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70acfdc7aaa'
down_revision = '78851f9ed7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('author_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'author_id')
    # ### end Alembic commands ###
