"""Init__

Revision ID: f973d4440ef3
Revises: 9d18ca623b11
Create Date: 2022-06-11 12:45:42.419156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f973d4440ef3'
down_revision = '9d18ca623b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blog_posts', 'users', ['author_id'], ['id'])
    op.add_column('comments', sa.Column('blog_post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'blog_posts', ['blog_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog_post_id')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    # ### end Alembic commands ###
